### PR TITLE
Fix ENOENT error when installing globally

### PR DESCRIPTION
**Pull request by karlhorky**
I am getting this ENOENT error when installing globally:

```bash
$ npm i -g testarmada-magellan-cli
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node5/5.11.1/bin/node" "/usr/local/bin/npm" "i" "-g" "testarmada-magellan-cli"
npm ERR! node v5.11.1
npm ERR! npm  v3.10.5
npm ERR! path /usr/local/lib/node_modules/testarmada-magellan-cli/bin/magellan
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/testarmada-magellan-cli/bin/magellan'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/testarmada-magellan-cli/bin/magellan'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/npm-debug.log
```

I think this is because the `magellan` file in `bin/` is not included in the npm package, correct?

### CODE REVIEW

**Comment by karlhorky** [comment]
Ping @chaseadamsio @Maciek416

**Comment by chaseadamsio** [comment]
Good catch! I'm not a big fan of the `files` property in `package.json` as I think it's often too explicit and would rather `.npmignore` `src`.

**Comment by karlhorky** [comment]
Cool, no worries, I can change the PR how you would like it. I just want to be able to install the package 😄  If you do want me to change it, please let me know how exactly you would like it.

Ping @Maciek416

**Comment by karlhorky** [comment]
Should we change this or just merge this as is? Right now this package is broken.

**Comment by chaseadamsio** [comment]
@karlhorky all set.

**Comment by karlhorky** [comment]
No problem, thanks for the package (and all the work you guys do on Magellan and other testing things)!

**Pull request merged**
